# Generated by Django 5.2 on 2025-06-13 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FluidArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FluidRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlushArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GlassArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OBDReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_city_running_kms', models.IntegerField()),
                ('pre_delivery_odo_kms', models.IntegerField()),
                ('current_odo_kms', models.IntegerField()),
                ('obd_running_kms', models.IntegerField()),
                ('obd_tampering', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaintArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RubberArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TyrePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VoltageInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.CharField(max_length=20)),
                ('engine_state', models.CharField(max_length=20)),
                ('interence', models.CharField(max_length=70)),
                ('recommendation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlushGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_gap', models.BooleanField()),
                ('action', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.flusharea')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.operations')),
            ],
        ),
        migrations.CreateModel(
            name='LiveParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.parameters')),
            ],
        ),
        migrations.CreateModel(
            name='RubberComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.rubberarea')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.status')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(max_length=100)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.performance')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.status')),
            ],
        ),
        migrations.CreateModel(
            name='PaintFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repainted', models.BooleanField()),
                ('action', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.paintarea')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.status')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.networkarea')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.status')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.interiorarea')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.interiorcategory')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.status')),
            ],
        ),
        migrations.CreateModel(
            name='GlassComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('recommendation', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.glassarea')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.status')),
            ],
        ),
        migrations.CreateModel(
            name='FluidLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.fluidarea')),
                ('in_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.fluidrange')),
                ('contamination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.status')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.documenttype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.status')),
            ],
        ),
        migrations.CreateModel(
            name='SystemCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_issues', models.PositiveIntegerField(default=0)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.status')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.system')),
            ],
        ),
        migrations.CreateModel(
            name='TyreCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('manufacturing_date', models.DateField()),
                ('remaining_life_percent', models.FloatField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.status')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.tyreposition')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars')),
                ('model', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=50, unique=True)),
                ('engine_cc', models.IntegerField()),
                ('bhp', models.CharField(max_length=20)),
                ('airbags', models.CharField(max_length=1)),
                ('mileage_kmpl', models.FloatField()),
                ('ncap_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('num_keys', models.IntegerField()),
                ('inspection_date', models.DateField()),
                ('health_score', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.customer')),
            ],
        ),
    ]
