# Generated by Django 5.2 on 2025-06-13 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarPDI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='inspected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspected_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tyrecondition',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='systemcheck',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='rubbercomponent',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='performancecheck',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='paintfinish',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='obdreading',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='networksystem',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='liveparameters',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='interiorcomponent',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='glasscomponent',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='flushgap',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='fluidlevel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicleenginetype'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehiclefueltype'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicletransmission'),
        ),
        migrations.AddField(
            model_name='liveparameters',
            name='interence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.voltageinference'),
        ),
    ]
