# Generated by Django 5.2 on 2025-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voltageinference',
            name='engine_state',
            field=models.CharField(choices=[('Off', 'Off'), ('On', 'On'), ('On (idling)', 'On (idling)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='voltageinference',
            name='interence',
            field=models.CharField(choices=[('Severely discharged battery', 'Severely discharged battery'), ('Low battery charge', 'Low battery charge'), ('Partially charged battery', 'Partially charged battery'), ('Normal resting voltage (healthy battery)', 'Normal resting voltage (healthy battery)'), ('Possibly overcharged or surface charge present', 'Possibly overcharged or surface charge present'), ('Normal charging voltage from alternator', 'Normal charging voltage from alternator'), ('Weak alternator or poor charging', 'Weak alternator or poor charging'), ('Overcharging – regulator or alternator fault possible', 'Overcharging – regulator or alternator fault possible')], max_length=70),
        ),
        migrations.AlterField(
            model_name='voltageinference',
            name='recommendation',
            field=models.CharField(choices=[('Recharge or replace battery immediately', 'Recharge or replace battery immediately'), ('Recharge soon, monitor usage', 'Recharge soon, monitor usage'), ('May require charging', 'May require charging'), ('NIL', 'NIL'), ('Recheck after load applied', 'Recheck after load applied'), ('Check alternator and connections', 'Check alternator and connections'), ('Inspect voltage regulator/alternator', 'Inspect voltage regulator/alternator')], max_length=100),
        ),
        migrations.AlterField(
            model_name='voltageinference',
            name='voltage',
            field=models.CharField(choices=[('< 11.8 V', '< 11.8 V'), ('11.8 – 12.0 V', '11.8 – 12.0 V'), ('12.1 – 12.3 V', '12.1 – 12.3 V'), ('12.4 – 12.7 V', '12.4 – 12.7 V'), ('> 12.7 V', '> 12.7 V'), ('13.7 – 14.7 V', '13.7 – 14.7 V'), ('< 13.5 V', '< 13.5 V'), ('> 14.8 V', '> 14.8 V')], max_length=20),
        ),
    ]
