# Generated by Django 5.2 on 2025-06-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0003_alter_voltageinference_engine_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintfinish',
            name='repainted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
