# Generated by Django 5.2 on 2025-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0004_alter_paintfinish_repainted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintfinish',
            name='repainted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
