# Generated by Django 5.2 on 2025-06-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0006_alter_paintfinish_repainted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flushgap',
            name='observation_gap',
            field=models.CharField(max_length=20),
        ),
    ]
