# Generated by Django 5.2 on 2025-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0007_alter_flushgap_observation_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voltageinference',
            name='engine_state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voltageinference',
            name='interence',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='voltageinference',
            name='recommendation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voltageinference',
            name='voltage',
            field=models.CharField(max_length=20),
        ),
    ]
