# Generated by Django 5.2 on 2025-06-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0008_vehicle_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='inspection_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
