# Generated by Django 5.2 on 2025-06-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0009_alter_vehicle_inspection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyrecondition',
            name='manufacturing_date',
        ),
    ]
