# Generated by Django 5.2 on 2025-06-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0010_remove_tyrecondition_manufacturing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='payment_amount',
            field=models.FloatField(default=500.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
