# Generated by Django 5.2 on 2025-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0011_vehicle_payment_amount_vehicle_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='payment_link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
