# Generated by Django 5.2 on 2026-01-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarPDI", "0012_vehicle_payment_link_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="engine_cc",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
