# Generated by Django 5.2 on 2026-01-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarPDI", "0013_alter_vehicle_engine_cc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="mileage_kmpl",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
