# Generated by Django 5.2 on 2026-01-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarPDI", "0014_alter_vehicle_mileage_kmpl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="num_keys",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
