# Generated by Django 5.2 on 2025-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_customuser_address_customuser_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True),
        ),
    ]
