# Generated by Django 5.2 on 2025-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_leave_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emp_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
