# Generated by Django 5.2 on 2025-06-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_customuser_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='abc',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
