# Generated by Django 5.2 on 2025-06-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_customuser_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='abc',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
