# Generated by Django 5.2 on 2025-12-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0010_alter_customuser_emp_id"),
        ("User", "0012_remove_customuser_is_admin_customuser_role"),
    ]

    operations = []
