# Generated by Django 5.2 on 2025-12-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0013_merge_20251227_1447"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
    ]
