# Generated by Django 5.2 on 2026-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0014_remove_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
