# Generated by Django 5.2 on 2026-01-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0015_userrole_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrole",
            name="description",
        ),
        migrations.AddField(
            model_name="roles",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
